num_caracs_2: ola_num_caracs_2.o num_caracs_2.o
        gcc $(CFLAGS) -o num_caracs_2 ola_num_caracs_2.o num_caracs_2.o
ola_num_caracs_2.o: ola_num_caracs_2.c num_caracs_2.h
        gcc $(CFLAGS) -c ola_num_caracs_2.c
num_caracs_2.o: num_caracs_2.c num_caracs_2.h
        gcc $(CFLAGS) -c num_caracs_2.c
clean:
        rm -f *.o num_caracs_2
